# Generated by Django 3.0.4 on 2020-03-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customers_rooms_screenings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customers')),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Screenings')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Reserved_seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bookings')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seats')),
            ],
        ),
    ]
