# Generated by Django 3.0.4 on 2020-03-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200307_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserved_seat',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='reserved_seat',
            old_name='seat_id',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='screenings',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='screenings',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='seats',
            old_name='room_id',
            new_name='room',
        ),
    ]
