# Generated by Django 3.0.4 on 2020-03-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200307_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='row',
            new_name='row_id',
        ),
        migrations.RenameField(
            model_name='seats',
            old_name='number',
            new_name='seat_number',
        ),
    ]
